const screens=[...document.querySelectorAll('.screen')];const nav=[...document.querySelectorAll('.nav-item')];let selected=[];let cookProgress=0;
const ingredients=[['🥦','西兰花','fiber'],['🥕','胡萝卜','vitamin'],['🍅','番茄','vitamin'],['🥬','菠菜','fiber'],['🐟','三文鱼','protein'],['🍚','糙米','grain'],['🍄','蘑菇','fiber'],['🥚','鸡蛋','protein']];
const upgrades=[['🧊','智能冰箱','新鲜食材随时可用',['保鲜时间 +20%','蔬菜品质 +1']],['⚡','节能灶台','更快、更少油的烹饪',['烹饪速度 +15%','用油量 -10%']],['📖','健康食谱库','解锁更多平衡搭配',['新食谱 +6','营养提示 +3']]];
function showScreen(name){screens.forEach(s=>s.classList.toggle('active',s.dataset.screen===name));nav.forEach(n=>n.classList.toggle('active',n.dataset.nav===name));}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.go)));nav.forEach(n=>n.addEventListener('click',()=>showScreen(n.dataset.nav)));
const grid=document.getElementById('ingredientGrid');grid.innerHTML=ingredients.map((x,i)=>`<button class="ingredient" data-i="${i}"><span class="check">✓</span><span class="emoji">${x[0]}</span><b>${x[1]}</b></button>`).join('');
grid.querySelectorAll('.ingredient').forEach(btn=>btn.addEventListener('click',()=>{const i=Number(btn.dataset.i);btn.classList.toggle('selected');selected=btn.classList.contains('selected')?[...selected,i]:selected.filter(v=>v!==i);document.getElementById('selectedCount').textContent=selected.length;document.getElementById('balanceMeter').style.width=`${Math.min(selected.length/4*100,100)}%`;const start=document.getElementById('cookStart');start.disabled=selected.length<4;start.innerHTML=selected.length<4?'至少选择4种食材 <span>→</span>':'开始烹饪 <span>→</span>';}));
document.getElementById('cookButton').addEventListener('click',()=>{if(cookProgress>=100){showScreen('upgrade');return}cookProgress=Math.min(cookProgress+20,100);document.getElementById('cookProgress').style.width=`${cookProgress}%`;document.getElementById('progressText').textContent=`${cookProgress}%`;document.getElementById('cookHint').textContent=cookProgress<100?'继续翻炒，让蔬菜保持清脆！':'完成！这是一份色彩丰富的健康餐。';document.getElementById('cookButton').innerHTML=cookProgress<100?'继续翻炒 <span>✦</span>':'查看厨房升级 <span>→</span>';});
document.getElementById('upgradeCards').innerHTML=upgrades.map((x,i)=>`<article class="upgrade"><div><div class="upgrade-visual"><span class="uicon">${x[0]}</span><span class="level-pill">LV.1 → LV.2</span></div><h3>${x[1]}</h3><p>${x[2]}</p><ul class="benefits">${x[3].map(v=>`<li>✓ ${v}</li>`).join('')}</ul><div class="stars">★ ★ <i>★</i></div></div><button data-up="${i}">解锁 · ${[80,100,120][i]} 金币</button></article>`).join('');document.querySelectorAll('[data-up]').forEach(btn=>btn.addEventListener('click',()=>{const cost=[80,100,120][Number(btn.dataset.up)];const coins=document.getElementById('coins');let current=Number(coins.textContent);if(btn.closest('.upgrade').classList.contains('unlocked'))return;if(current<cost){btn.textContent='金币不足';return}coins.textContent=current-cost;btn.closest('.upgrade').classList.add('unlocked');btn.textContent='✓ 已解锁';}));
